from typing import Optional


class AlarmEvent:

    def __init__(self, name: Optional[str] = None):
        self.attr_name = name
        self.dict_name = name
        self.attr_acked = None
        self.attr_ack_data = None
        self.attr_activeData = None
        self.attr_cleared = None
        self.attr_clearedData = None
        self.attr_count = None
        self.attr_displayPath = None
        self.attr_displayPathOrSource = None
        self.attr_extension = None
        self.attr_getAckData = None
        self.attr_getActiveData = None
        self.attr_getClearedData = None
        self.attr_getCount = None
        self.attr_getDisplayPath = None
        self.attr_getDisplayPathOrSource = None
        self.attr_getExtension = None
        self.attr_getId = None
        self.attr_getLabel = None
        self.attr_getLastEventState = None
        self.attr_getName = None
        self.attr_getNotes = None
        self.attr_getPriority = None
        self.attr_getProperties = None
        self.attr_getSource = None
        self.attr_getState = None
        self.attr_getValues = None
        self.attr_hashCode = None
        self.attr_id = None
        self.attr_isAcked = None
        self.attr_isCleared = None
        self.attr_isExtended = None
        self.attr_isInherited = None
        self.attr_isShelved = None
        self.attr_label = None
        self.attr_lastEventState = None
        self.attr_name = None
        self.attr_notes = None
        self.attr_notify = None
        self.attr_notifyAll = None
        self.attr_priority = None
        self.attr_properties = None
        self.attr_shelved = None
        self.attr_source = None
        self.attr_sourceEvent = None
        self.attr_state = None
        self.attr_values = None
        self.dict_event_id = None
        self.dict_event_state = None
        self.dict_is_acked = None
        self.dict_is_cleared = None
        self.dict_is_shelved = None
        self.dict_ack_data = None
        self.dict_acked = None
        self.dict_cleared = None
        self.dict_cleared_data = None
        self.dict_count = None
        self.dict_display_path = None
        self.dict_display_path_or_source = None
        self.dict_extension = None
        self.dict_id = None
        self.dict_label = None
        self.dict_last_event_state = None
        self.dict_name = None
        self.dict_notes = None
        self.dict_priority = None
        self.dict_properties = None
        self.dict_property_values = None
        self.dict_shelved = None
        self.dict_source = None
        self.dict_state = None
        self.event_time = None
        self.func_active_data = None
        self.func_ack_data = None
        self.func_cleared_data = None
        self.func_count = None
        self.func_display_path = None
        self.func_label = None
        self.func_last_event_state = None
        self.func_priority = None
        self.func_state = None
        self.func_is_acked = None
        self.func_is_cleared = None
        self.func_is_shelved = None

    def __str__(self):
        return str(self.__dict__)
